config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'
  resources :messages

  get  '/dashboard',             to: 'dashboard#show'
  get  '/export_all',            to: 'dashboard#export_all'
  post '/twilio/create',         to: 'twilio#create'
  get  '/logout',                to: 'sessions#destroy'
  get  '/auth/twitter/callback', to: 'sessions#create'
  get  '/agents/:id',            to: 'agents#show',     as: 'agent'
  get  '/tecnicos/:id',          to: 'tecnicos#show',   as: 'tecnico'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @messages = Message.recent
  end

  private

  def export_all
    Exporter.run
  end
end

app/views/dashboard/show.html.slim
html
  head
    link[rel="stylesheet" href="assets/bootstrap.min.css" type="text/css"]
    link[href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css"]
    link[href="http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css"]
    link[rel="stylesheet" href="assets/animate.min.css" type="text/css"]
    link[rel="stylesheet" href="assets/creative.css" type="text/css"]
  = render partial: "/partials/navbar"
  section
    .row
      .col-lg-12.text-center
        h1.section-heading
          | Dashboard
    .container
      .row
        .col-lg-4.col-md-6.text-center
          h3
            | Stream
          p.text-muted
            - @messages.each do |message|
              .text
                = link_to message.sender_short_name, message.from
                | :
                br
                = message.body
        .col-lg-4.col-md-6.text-center.stats
          h3
            | Stats
          .text-muted
            = MessageStatsPresenter.to_readable
            br
            br
            hr
        .col-lg-4.col-md-6.text-center
          h3
            | Send Message
          .text-muted
            = form_tag twilio_create_path, method: :post do
              = text_field_tag 'to', '', placeholder: 'Phone Number'
              br
              br
              = text_field_tag 'body', '', placeholder: 'Text Body'
              br
              br
              = submit_tag 'Send'
        .col-lg-4.col-md-6.text-center
          h3
            | Export
          .text-muted
            = link_to 'Export Archive to CSV', Exporter.run
  script[src="assets/jquery.js"]
  script[src="assets/bootstrap.min.js"]
  script[src="assets/jquery.easing.min.js"]